### ISSUE TITLE
someting worong with download the crx in chrome webstore

### ISSUE THREAD

**Issue by DLCnow** [todaylg/Anime-New-Tab#1]
Hello todayLG , I've reset my PC recently and want to reinstall the Anime-New-Tab in chrome webstore , but I got this:

![errorshotcut](https://user-images.githubusercontent.com/24190152/44842242-e6ea4a80-ac77-11e8-8902-d1e117cc9416.png)

1. my browse's version v68.0.3440.106
2. I had opened a VPN called sslspeedly
3. OS is windows 10

Hope your reply , thk bro!

**Comment by todaylg** [comment]
sslspeedy's problem?lantern

**Comment by todaylg** [comment]
sslspeedy's problem?

**Comment by todaylg** [comment]
sslspeedy's problem? lantern successful download

**Comment by DLCnow** [comment]
thk ag , it doesn't seems like VPN's fault , but it works now.

**Comment by DLCnow** [comment]
BTW , Megumi is really nice 👍

**Comment by todaylg** [comment]
I prefer Miku now.haha

**Comment by todaylg** [comment]
I prefer Miku now.hahaha
chuan chuan  yep
