### ISSUE TITLE
There are someting to be optimized

### ISSUE THREAD

**Issue by DLCnow** [todaylg/Anime-New-Tab#2]
Hello , G
  Recently I used the ANT , I found a piece of place could be optimized.Have a look at this pic.
![image](https://user-images.githubusercontent.com/24190152/53860356-aa7b1b00-401b-11e9-899f-3487d3122b69.png)
  If the background color closed to white , the font color was hard to read , this make me have no choice but to change my bg.(But sometimes I really dont want to change!!)
  Can it being put on the agenda? ^_^

**Comment by todaylg** [comment]
Although such scenes the 'fontColor' option is hard to read，but you still know it’s  there。
That’s OK
